# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/eth_ref_clk.xdc

# Block Designs: bd/echo_server_mem_test/echo_server_mem_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test || ORIG_REF_NAME==echo_server_mem_test} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_microblaze_0_0/echo_server_mem_test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_microblaze_0_0 || ORIG_REF_NAME==echo_server_mem_test_microblaze_0_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_dlmb_v10_0/echo_server_mem_test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_dlmb_v10_0 || ORIG_REF_NAME==echo_server_mem_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_ilmb_v10_0/echo_server_mem_test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_ilmb_v10_0 || ORIG_REF_NAME==echo_server_mem_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_dlmb_bram_if_cntlr_0/echo_server_mem_test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==echo_server_mem_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_ilmb_bram_if_cntlr_0/echo_server_mem_test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==echo_server_mem_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_lmb_bram_0/echo_server_mem_test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_lmb_bram_0 || ORIG_REF_NAME==echo_server_mem_test_lmb_bram_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_xbar_0/echo_server_mem_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_xbar_0 || ORIG_REF_NAME==echo_server_mem_test_xbar_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_microblaze_0_axi_periph_0/echo_server_mem_test_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==echo_server_mem_test_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_microblaze_0_axi_intc_0/echo_server_mem_test_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_microblaze_0_axi_intc_0 || ORIG_REF_NAME==echo_server_mem_test_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_microblaze_0_xlconcat_0/echo_server_mem_test_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_microblaze_0_xlconcat_0 || ORIG_REF_NAME==echo_server_mem_test_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_mdm_1_0/echo_server_mem_test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_mdm_1_0 || ORIG_REF_NAME==echo_server_mem_test_mdm_1_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_clk_wiz_1_0/echo_server_mem_test_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_clk_wiz_1_0 || ORIG_REF_NAME==echo_server_mem_test_clk_wiz_1_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_rst_clk_wiz_1_100M_0/echo_server_mem_test_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==echo_server_mem_test_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_mig_7series_0_0/echo_server_mem_test_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_mig_7series_0_0 || ORIG_REF_NAME==echo_server_mem_test_mig_7series_0_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_axi_ethernetlite_0_0/echo_server_mem_test_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_axi_ethernetlite_0_0 || ORIG_REF_NAME==echo_server_mem_test_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_axi_timer_0_0/echo_server_mem_test_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_axi_timer_0_0 || ORIG_REF_NAME==echo_server_mem_test_axi_timer_0_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_axi_uartlite_0_0/echo_server_mem_test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_axi_uartlite_0_0 || ORIG_REF_NAME==echo_server_mem_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_mii_to_rmii_0_0/echo_server_mem_test_mii_to_rmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_mii_to_rmii_0_0 || ORIG_REF_NAME==echo_server_mem_test_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_axi_smc_1/echo_server_mem_test_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_axi_smc_1 || ORIG_REF_NAME==echo_server_mem_test_axi_smc_1} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_rst_mig_7series_0_81M_2/echo_server_mem_test_rst_mig_7series_0_81M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_rst_mig_7series_0_81M_2 || ORIG_REF_NAME==echo_server_mem_test_rst_mig_7series_0_81M_2} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_axi_dma_0_0/echo_server_mem_test_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_axi_dma_0_0 || ORIG_REF_NAME==echo_server_mem_test_axi_dma_0_0} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_system_ila_1_1/echo_server_mem_test_system_ila_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_system_ila_1_1 || ORIG_REF_NAME==echo_server_mem_test_system_ila_1_1} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_system_ila_0_3/echo_server_mem_test_system_ila_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_system_ila_0_3 || ORIG_REF_NAME==echo_server_mem_test_system_ila_0_3} -quiet] -quiet

# IP: bd/echo_server_mem_test/ip/echo_server_mem_test_inverter_module_0_0/echo_server_mem_test_inverter_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_server_mem_test_inverter_module_0_0 || ORIG_REF_NAME==echo_server_mem_test_inverter_module_0_0} -quiet] -quiet

# XDC: /home/jack/VERILOG/4_29_onward/axis_ip_attempt1_part2/memory_test/memory_test.gen/sources_1/bd/echo_server_mem_test/echo_server_mem_test_ooc.xdc
