# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jack/VERILOG/4_29_onward/axis_ip_attempt1/memory_test/memory_test.srcs/sources_1/bd/echo_server_mem_test/ip/echo_server_mem_test_xbar_0/echo_server_mem_test_xbar_0.xci
# IP: The module: 'echo_server_mem_test_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jack/VERILOG/4_29_onward/axis_ip_attempt1/memory_test/memory_test.gen/sources_1/bd/echo_server_mem_test/ip/echo_server_mem_test_xbar_0/echo_server_mem_test_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'echo_server_mem_test_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jack/VERILOG/4_29_onward/axis_ip_attempt1/memory_test/memory_test.srcs/sources_1/bd/echo_server_mem_test/ip/echo_server_mem_test_xbar_0/echo_server_mem_test_xbar_0.xci
# IP: The module: 'echo_server_mem_test_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jack/VERILOG/4_29_onward/axis_ip_attempt1/memory_test/memory_test.gen/sources_1/bd/echo_server_mem_test/ip/echo_server_mem_test_xbar_0/echo_server_mem_test_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'echo_server_mem_test_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
